/*
 * Copyright (c) Forge Development LLC
 * SPDX-License-Identifier: LGPL-2.1-only
 */
/*
 * This source file was generated by the Gradle 'init' task
 */
package net.minecraftforge.multi_release.gradle.internal;

import net.minecraftforge.gradleutils.shared.EnhancedPlugin;
import net.minecraftforge.multi_release.gradle.MultiReleaseExtension;
import org.gradle.api.Project;

import javax.inject.Inject;

abstract class MultiReleasePlugin extends EnhancedPlugin<Project> {
    static final String NAME = "multi-release";
    static final String DISPLAY_NAME = "Multi-Release Java";

    @Inject
    public MultiReleasePlugin() {
        super(NAME, DISPLAY_NAME);
    }

    @Override
    public void setup(Project project) {
        // TODO [Gradle] Support overriding the extension name using a Gradle or system property
        project.getExtensions().create(MultiReleaseExtension.NAME, MultiReleaseExtensionImpl.class, MultiReleaseExtension.NAME);
    }
}
